-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  action text NOT NULL,
  details text,
  is_read boolean NOT NULL DEFAULT false,
  user_id uuid,
  CONSTRAINT activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.child_breastfeeding (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  child_record_id uuid NOT NULL,
  month_number integer NOT NULL,
  is_exclusive boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT child_breastfeeding_pkey PRIMARY KEY (id),
  CONSTRAINT child_breastfeeding_child_record_id_fkey FOREIGN KEY (child_record_id) REFERENCES public.child_records(id)
);
CREATE TABLE public.child_immunizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  child_record_id uuid NOT NULL,
  immunization_type text NOT NULL,
  date_given date,
  age text,
  weight_kg numeric,
  height_cm numeric,
  nutritional_status text,
  admitted_by text,
  immunized_by text,
  next_visit date,
  remarks text,
  admission_time time without time zone,
  departure_time time without time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT child_immunizations_pkey PRIMARY KEY (id),
  CONSTRAINT child_immunizations_child_record_id_fkey FOREIGN KEY (child_record_id) REFERENCES public.child_records(id)
);
CREATE TABLE public.child_measurements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  child_record_id uuid NOT NULL,
  measurement_date date NOT NULL DEFAULT CURRENT_DATE,
  weight_kg numeric,
  height_cm numeric,
  bmi numeric,
  nutrition_status text,
  muac_cm numeric,
  recorded_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT child_measurements_pkey PRIMARY KEY (id),
  CONSTRAINT child_measurements_child_record_id_fkey FOREIGN KEY (child_record_id) REFERENCES public.child_records(id),
  CONSTRAINT child_measurements_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.child_mother_immunizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  child_record_id uuid NOT NULL,
  immunization_type text NOT NULL,
  date_given date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT child_mother_immunizations_pkey PRIMARY KEY (id),
  CONSTRAINT child_mother_immunizations_child_record_id_fkey FOREIGN KEY (child_record_id) REFERENCES public.child_records(id)
);
CREATE TABLE public.child_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  child_id text NOT NULL UNIQUE,
  first_name text,
  last_name text,
  dob date,
  sex text,
  place_of_birth text,
  mother_name text,
  father_name text,
  guardian_name text,
  nhts_no text,
  philhealth_no text,
  weight_kg numeric,
  height_cm numeric,
  bmi numeric,
  nutrition_status text,
  last_checkup date,
  created_at timestamp with time zone DEFAULT now(),
  address text,
  bhs_name text,
  family_number text,
  delivery_time time without time zone,
  birth_order text,
  delivery_type text,
  mother_age integer,
  contact_no text,
  guardian_relationship text,
  nearest_landmark text,
  nbs_referral_date date,
  nbs_result text,
  birth_attendant text,
  aog_at_birth text,
  smoking_history text,
  birth_weight text,
  child_name text,
  place_of_delivery text,
  vitamin_a_amount text,
  vitamin_a_date date,
  is_synced boolean DEFAULT false,
  updated_at timestamp with time zone,
  CONSTRAINT child_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.child_supplementation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  child_record_id uuid NOT NULL,
  supplement_type text NOT NULL,
  date_given date,
  amount text,
  administered_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT child_supplementation_pkey PRIMARY KEY (id),
  CONSTRAINT child_supplementation_child_record_id_fkey FOREIGN KEY (child_record_id) REFERENCES public.child_records(id)
);
CREATE TABLE public.dispensing (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  prescription_id uuid NOT NULL,
  dispensed_by uuid NOT NULL,
  dispensed_date timestamp with time zone NOT NULL DEFAULT now(),
  quantity_dispensed integer NOT NULL CHECK (quantity_dispensed > 0),
  status text NOT NULL DEFAULT 'Dispensed'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT dispensing_pkey PRIMARY KEY (id),
  CONSTRAINT dispensing_prescription_id_fkey FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id),
  CONSTRAINT dispensing_dispensed_by_fkey FOREIGN KEY (dispensed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.follow_up_visit (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL,
  time text,
  reason text,
  status text DEFAULT 'Scheduled'::text,
  created_at timestamp with time zone DEFAULT now(),
  notes text,
  patient_display_id text,
  confirmed_by uuid,
  visit_type text DEFAULT 'maternal'::text,
  CONSTRAINT follow_up_visit_pkey PRIMARY KEY (id),
  CONSTRAINT follow_up_visit_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_name text NOT NULL,
  category text,
  quantity integer NOT NULL DEFAULT 0,
  status USER-DEFINED DEFAULT 'Normal'::inventory_status,
  expiry_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  sku text,
  batch_no text,
  supply_source text,
  owner_role text DEFAULT 'BHW'::text,
  unit text,
  min_stock_level integer DEFAULT 10,
  reorder_quantity integer DEFAULT 50,
  CONSTRAINT inventory_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventory_id uuid NOT NULL,
  movement_type text NOT NULL CHECK (movement_type = ANY (ARRAY['IN'::text, 'OUT'::text, 'ADJUSTMENT'::text, 'WASTE'::text])),
  quantity_change integer NOT NULL,
  quantity_before integer,
  quantity_after integer,
  reason text,
  reference_type text,
  reference_id text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  notes text,
  CONSTRAINT inventory_movements_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_movements_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id),
  CONSTRAINT inventory_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.maternal_medical_conditions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mother_record_id uuid NOT NULL,
  condition_type text NOT NULL,
  condition_category text NOT NULL,
  is_present boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT maternal_medical_conditions_pkey PRIMARY KEY (id),
  CONSTRAINT maternal_medical_conditions_mother_record_id_fkey FOREIGN KEY (mother_record_id) REFERENCES public.mother_records(id)
);
CREATE TABLE public.maternal_menstrual_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mother_record_id uuid NOT NULL,
  lmp date,
  edc date,
  age_of_menarche integer,
  menstruation_duration integer,
  bleeding_amount text,
  age_first_period integer,
  risk_code text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT maternal_menstrual_history_pkey PRIMARY KEY (id),
  CONSTRAINT maternal_menstrual_history_mother_record_id_fkey FOREIGN KEY (mother_record_id) REFERENCES public.mother_records(id)
);
CREATE TABLE public.maternal_obstetrical_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mother_record_id uuid NOT NULL,
  gravida text,
  outcome text,
  sex text,
  delivery_type text,
  delivered_at text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT maternal_obstetrical_history_pkey PRIMARY KEY (id),
  CONSTRAINT maternal_obstetrical_history_mother_record_id_fkey FOREIGN KEY (mother_record_id) REFERENCES public.mother_records(id)
);
CREATE TABLE public.maternal_obstetrical_score (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mother_record_id uuid NOT NULL UNIQUE,
  g_score integer,
  p_score integer,
  term integer,
  preterm integer,
  abortion integer,
  living_children integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT maternal_obstetrical_score_pkey PRIMARY KEY (id),
  CONSTRAINT maternal_obstetrical_score_mother_record_id_fkey FOREIGN KEY (mother_record_id) REFERENCES public.mother_records(id)
);
CREATE TABLE public.maternal_pregnancy_outcomes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mother_record_id uuid NOT NULL,
  date_terminated date,
  delivery_type text,
  outcome text,
  child_sex text,
  birth_weight_grams numeric,
  age_weeks integer,
  place_of_birth text,
  attended_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT maternal_pregnancy_outcomes_pkey PRIMARY KEY (id),
  CONSTRAINT maternal_pregnancy_outcomes_mother_record_id_fkey FOREIGN KEY (mother_record_id) REFERENCES public.mother_records(id)
);
CREATE TABLE public.maternal_supplementation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mother_record_id uuid NOT NULL,
  supplement_type text NOT NULL,
  date_given date,
  amount text,
  administered_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT maternal_supplementation_pkey PRIMARY KEY (id),
  CONSTRAINT maternal_supplementation_mother_record_id_fkey FOREIGN KEY (mother_record_id) REFERENCES public.mother_records(id)
);
CREATE TABLE public.maternal_treatment_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mother_record_id uuid NOT NULL,
  visit_date date,
  arrival_time time without time zone,
  departure_time time without time zone,
  height_cm numeric,
  weight_kg numeric,
  bp text,
  muac_cm numeric,
  bmi numeric,
  aog_weeks integer,
  fh_cm numeric,
  fhb text,
  loc text,
  presentation text,
  fe_fa text,
  admitted text,
  examined text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT maternal_treatment_records_pkey PRIMARY KEY (id),
  CONSTRAINT maternal_treatment_records_mother_record_id_fkey FOREIGN KEY (mother_record_id) REFERENCES public.mother_records(id)
);
CREATE TABLE public.maternal_vaccinations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mother_record_id uuid NOT NULL,
  vaccine_type text NOT NULL,
  date_given date,
  administered_by text,
  batch_no text,
  remarks text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  is_synced boolean DEFAULT false,
  CONSTRAINT maternal_vaccinations_pkey PRIMARY KEY (id),
  CONSTRAINT maternal_vaccinations_mother_record_id_fkey FOREIGN KEY (mother_record_id) REFERENCES public.mother_records(id)
);
CREATE TABLE public.mother_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id text NOT NULL UNIQUE,
  first_name text NOT NULL,
  middle_name text,
  last_name text NOT NULL,
  age integer,
  contact_no text,
  weeks integer,
  last_visit date,
  risk_level USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  purok text,
  street text,
  updated_at timestamp with time zone,
  user_id uuid,
  sms_notifications_enabled boolean DEFAULT true,
  dob date,
  blood_type text,
  family_folder_no text,
  nhts_no text,
  philhealth_no text,
  allergy_history text,
  family_planning_history text,
  is_synced boolean DEFAULT false,
  CONSTRAINT mother_records_pkey PRIMARY KEY (id),
  CONSTRAINT patients_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid,
  type text NOT NULL,
  message text NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.prescriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_type text NOT NULL,
  patient_record_id uuid NOT NULL,
  item_name text NOT NULL,
  quantity integer NOT NULL,
  instructions text,
  date_given timestamp with time zone NOT NULL DEFAULT now(),
  issuer_id uuid,
  inventory_item_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone,
  status text NOT NULL DEFAULT 'Pending'::text,
  CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT prescriptions_issuer_id_fkey FOREIGN KEY (issuer_id) REFERENCES public.profiles(id),
  CONSTRAINT prescriptions_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.inventory(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  updated_at timestamp with time zone,
  full_name text,
  role text NOT NULL CHECK (role = ANY (ARRAY['Admin'::text, 'BHW'::text, 'BNS'::text, 'Midwife'::text, 'USER/MOTHER/GUARDIAN'::text])),
  assigned_purok text,
  preferences jsonb,
  first_name text,
  last_name text,
  middle_initial text,
  birth_date date,
  contact_no text,
  avatar_url text,
  user_id_no text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.requestions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  worker_id uuid,
  request_type text NOT NULL,
  target_table text NOT NULL,
  request_data jsonb,
  status text NOT NULL DEFAULT 'Pending'::text,
  target_record_id uuid NOT NULL,
  role_source text DEFAULT 'BHW'::text,
  CONSTRAINT requestions_pkey PRIMARY KEY (id),
  CONSTRAINT requestions_worker_id_fkey FOREIGN KEY (worker_id) REFERENCES public.profiles(id)
);